Method overloading is not possible in Python

In [ ]:
class A():
    def display(self,x,y=None):
        if(y==None):
            print(x)
        else:
            print(x,y)
ob = A()
ob.display(2)
ob.display(9,5)

- (+) b/w any two object of class will autometicaly call (__add__)
- (-) b/w any two object of class will autometicaly call (__sub__)
- (*) b/w any two object of class will autometicaly call (__mul__)
- (/) b/w any two object of class will autometicaly call (__truediv__)
- (//) b/w any two object of class will autometicaly call (__floordiv__)
- (%) b/w any two object of class will autometicaly call (__mod__)
- (**) b/w any two object of class will autometicaly call (__pow__)
- (<) b/w any two object of class will autometicaly call (__lt__)
- (>) b/w any two object of class will autometicaly call (__gt__)
- (<=) b/w any two object of class will autometicaly call (__le__)
- (>=) b/w any two object of class will autometicaly call (__ge__)
- (!=) b/w any two object of class will autometicaly call (__ne__)
- (==) b/w any two object of class will autometicaly call (__eq__)

In [ ]:
class B():
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __add__(self,other):
        x = self.x + other.x
        y = self.y + other.y
        return (x,y)
    def __sub__(self,su):
        x = self.x - su.x
        y = self.y - su.y
        return (x,y)
    def __mul__(self,ot):
        x = self.x * ot.x
        y = self.y * ot.y
        return(x,y)
    def __floordiv__(self,fd):
        x = self.x // fd.x
        y = self.y // fd.y
        return(x,y)
p1 = B(20,30)
p2 = B(20,30)
print(p1//p2)

In [ ]:
class Student():
    def __init__(self,name,rn,age,marks):
        self.name = name
        self.rn = rn 
        self.age = age 
        self.marks = marks
    def display(self):
        print("Student name : ",self.name)
        print("Student roll no. : ",self.rn)
        print("Student Age : ",self.age)
        print("Student Marks : ",self.marks)
    def __eq__(self,other):
        if(self.marks == other.marks):
            return "Marks are same!"
        else:
            return "Marks are Not same!"
s1 = Student("asdf",12,19,87)
s2 = Student("ghjk",23,20,87)
print(s1==s2)

### Inheritance :
    Parent class - Base class
    child class - Derived class
    1. Single
    2. Multiple
    3. Multi level
    4. Hierarchical
    5. Hybrid

In [ ]:
class A():
    def demo(self):
        print("class A")
class B(A):
    def dis(self):
        print("class B")
ob = B()
ob.demo()
ob.dis()

In [ ]:
# create a class Book(Base) which has name,n,author,publisher,isbn,year as variables and display method
# create a class TextBook(Derived) which has course and display method including course

class Book():
    def __init__(self):
        self.name = input("name : ") 
        self.n = input("n : ")
        self.author = input("author : ")
        self.publisher = input("publisher : ")
        self.isbn = input("isbn : ")
        self.year = input("year : ")
    def display(self):
        print("Name : ",self.name)
        print("N : ",self.n)
        print("Author : ",self.author)
        print("Publisher : ",self.publisher)
        print("ISBN : ",self.isbn)
        print("Year : ",self.year)
class TextBook(Book):
    def __init__(self):
        super().__init__()
        self.course = input("course : ")
    def display(self):
        super().display()
        print("Course : ",self.course)
ob = TextBook()
ob.display()

In [ ]:
# Method resolution Order
class Person():
    def __init__(self):
        self.name = input("name : ")
        self.age = input("Age : ")
class Car():
    def __init__(self):
        self.model = input("model : ")
        self.color = input("color : ")
class Parking(Person,Car):
    def __init__(self):
        Person.__init__(self)
        Car.__init__(self)
        self.parkingNo = input("parkingNo : ")
    def display(self):
        print("Name : ",self.name)
        print("Age : ",self.age)
        print("Model : ",self.model)
        print("Color : ",self.color)
        print("Parking No. : ",self.parkingNo)
ob = Parking()
ob.display()

# MRO(Method Resolution Order)

In [ ]:
class A:
    def rk(self):
        print(" In class A")
class B:
    def rk(self):
        print(" In class B")
class C(A, B):
     def rk(self):
            pass
r = C()
print(C.__mro__)

In [ ]:
class A:
     pass
class B:
     pass
class C:
     pass
class X(A,B):
     pass
class Y(C,A,B):
     pass
class Z(A):
     pass
class P(Z,Y,X):
     pass
print(P.__mro__)

In [ ]:
class Vehicle():
    def __init__(self):
        self.name = input("Enter Name : ")
        self.mileage = input("Enter Mileage : ")
        self.sc = int(input("Enter Seating Capacity : "))

    def display(self):
        print("Name : ",self.name)
        print("Mileage : ",self.mileage)
        print("Seating Capacity : ",self.sc)
    def fair(self):
        return self.sc*100
class Bus(Vehicle):
    def fair(self):
        return self.sc*100 + self.sc*10
class Car(Vehicle):
    def fair(self):
        return self.sc*100 + self.sc*10
bus = Bus()
print(bus.fair())

In [ ]:
class Matrix():
    def __init__(self):
        self.row = 0
        self.col = 0
    def get_Row(self):
        self.row = int(input("Enter Row : "))
    def get_Col(self):
        self.col = int(input("Enter Column : "))
    def set_Element(self):
        self.mat=[]
        for i in range(self.row):
            l=[]
            for j in range(self.col):
                n = int(input(f"Enter Element {i,j} : "))
                l.append(n)
            self.mat.append(l)
        print(self.mat) 
    def __add__(self,other):
        if((self.row == other.row) and (other.col==self.col)):
            self.ans = []
            for i in range(self.row):
                l = []
                for j in range(self.col):
                    n = self.mat[i][j] + other.mat[i][j]
                    l.append(n)
                self.ans.append(l)
            print(self.ans)
        else:
            print("Matrices are not Addable.")
    def __mul__(m1,m2):
        if(m1.col == m2.row):
            res = []
            for i in range(m1.row):
                l = []
                for j in range(m2.col):
                    n = 0
                    for k in range(m2.row):
                        n += m1.mat[i][k]*m2.mat[k][j]
                    l.append(n)
                res.append(l)
            print(res)
m = Matrix()
m.get_Row()
m.get_Col()
m.set_Element()
m1 = Matrix()
m1.get_Row()
m1.get_Col()
m1.set_Element()
m * m1

In [ ]:
# Implement the following hierarchy . The Staff function has name and salary as its data members, the derived class 
# Teaching has subject as its data member and the class NonTeaching has department as its data member. The derived class 
# method overrides (extends) the methods of the base class

class Staff():
    def __init__(self):
        self.name = input("Enter Name : ")
        self.sal = input("Enter Sal : ")
class Teaching(Staff):
    def __init__(self):
        Staff.__init__()
        self.sub = input("Enter Subject : ")
class NonTeaching(Staff):
    def __init__(self):
        Staff.__init__()
        self.dep = input("Enter Department : ")
ch1 = Teaching()
ch2 = NonTeaching()

## Abstraction : 

In [ ]:
from abc import ABC,abstractmethod # abc(abstract base class) <- module ABC <- Function
class AbDemo(ABC):
    @abstractmethod 
    def demo(self):
        pass
class Base(AbDemo):
    def demo(self):
        print('Base class.')
    
b = Base()
b.demo()

In [ ]:
from abc import ABC,abstractmethod
class Shape(ABC):
    @abstractmethod
    def calculate_area(self):
        pass
class Rectangle(Shape):
    def __gt__(self,other):
        return self.rarea > other.rarea
    def calculate_area(self,l,b):
        self.rarea = l*b
        print("Area of Rectangle : ",self.rarea)
class Circle(Shape):
    def calculate_area(self,r):
        carea = 3.14*(r**2)
        print("Area of Circle : ",carea)
r1 = Rectangle()
r1.calculate_area(10,20)
r2 = Rectangle()
r2.calculate_area(20,30)
print(r1>r2)
print(r2>r1)
print(Circle.__mro__)

Imagine you own a call center. Use the following abstract class template to create three more classes, Respondent, 
Manager, and Director that inherit this Employee Abstract Class.
from abc import ABC, abstractmethod
class Employee(ABC):
 @abstractmethod
 def receive_call(self):
 pass
 
 @abstractmethod
 def end_call(self):
 pass
 @abstractmethod
 def is_free(self):
 pass
 
 @abstractmethod
 def get_rank(self):
 pass

In [1]:
from abc import ABC, abstractmethod
class Employee(ABC):
    @abstractmethod
    def receive_call(self):
         pass
    @abstractmethod
    def end_call(self):
        pass
    @abstractmethod
    def is_free(self):
        pass
    @abstractmethod
    def get_rank(self):
        pass
class Respondent(Employee):
    def __init__(self):
        self.name = input("Enter Name : ")
        self.id = input("Enter ID : ")
        self.rank = 3
        self.free = True
    def receive_call(self):
        print("call received by ",self.name)
        self.free = False
    def end_call(self):
        print("call ended")
        self.free = True
    def is_free(self):
        return self.free
    def get_rank(self):
        return self.rank
class Manager(Employee):
    def __init__(self):
        self.name = input("Enter Name : ")
        self.id = input("Enter ID : ")
        self.rank = 2
        self.free = True
    def receive_call(self):
        print("call received by ",self.name)
        self.free = False
    def end_call(self):
        print("call ended")
        self.free = True
    def is_free(self):
        return self.free
    def get_rank(self):
        return self.rank
class Director(Employee):
    def __init__(self):
        self.name = input("Enter Name : ")
        self.id = input("Enter ID : ")
        self.rank = 1
        self.free = True
    def receive_call(self):
        print("call received by ",self.name)
        self.free = False
    def end_call(self):
        print("call ended")
        self.free = True
    def is_free(self):
        return self.free
    def get_rank(self):
        return self.rank
class Call():
    def __init__(self):
        self.id = input("Enter ID : ")
        self.name = input("Enter Name : ")
        self.assign = False
class CallHandler():
    respondents = []
    managers = []
    directors= []
    def add_Employee(self,ob):
        if(ob.rank==1):
            CallHandler.directors.append(ob)
        elif(ob.rank==2):
            CallHandler.managers.append(ob)
        elif(ob.rank==3):
            CallHandler.respondents.append(ob)
    def dispatch_call(self,call):
        for i in CallHandler.respondents:
            if(i.is_free()):
                i.receive_call()
                Call.assign = True
                break
        else:
            for j in CallHandler.managers:
                if(j.is_free()):
                    j.receive_call()
                    Call.assign = True
                    break
            else:
                for k in CallHandler.directors:
                    if(k.is_free()):
                        k.receive_call()
                        call.assign = True
                        break
                else:
                    print("Sorry! All employees are currently busy.")
r1 = Respondent()
# r2 = Respondent()
# r3 = Respondent()
m1 = Manager()
# m2 = Manager()
d1 = Director()
ch = CallHandler()
ch.add_Employee(r1)
# ch.add_Employee(r2)
# ch.add_Employee(r3)
ch.add_Employee(m1)
# ch.add_Employee(m2)
ch.add_Employee(d1)
c = Call()
ch.dispatch_call(c)

Enter Name : asdf
Enter ID : 1
Enter Name : qwer
Enter ID : 2
Enter Name : zxcv
Enter ID : 3
Enter ID : 101
Enter Name : nirav
call received by  asdf


In [5]:
from abc import ABC,abstractmethod
class Employee(ABC):
    def Data(self):
        self.name = input("Enter Name : ")
        self.id = input("Enter ID : ")
        self.sal = input("Enter Salary : ")
    def display(self):
        print("Name : ",self.name)
        print("ID : ",self.id)
        print("Salary : ",self.sal)
    def get_Sal(self):
        return self.sal
    @abstractmethod
    def emp_id(self):
        pass
class Perks(Employee):
    def __init__(self):
        self.da = 0
        self.hra = 0
        self.pf = 0
    def emp_id(self):
        pass
    def Cal_Perk(self):
        self.da = 0.35 * self.sal
        self.hra = 0.17 * self.sal
        self.da = 0.12 * self.sal
        self.total = self.da + self.hra - self.pf
        print(self.da)
        print(self.hra)
        print(self.da)
        print(self.total)
class NetSalary(Perks):
    def emp_id(self):
        pass
    def cal_netsalary(self):
        self.final = self.sal + self.total
        print(self.final)
e = Employee()
e.Data()
ns = NetSalary()
ns.cal_netsalary()

TypeError: Can't instantiate abstract class Employee with abstract methods emp_id

## NumPy : Numerical Python
- using for numerical Calculations.
###### Creatign NumPy Array
- in array we can add list,tuple 
- Dimentions of array 
1. 0-D
2. 1-D
3. 2-D
4. 3-D
- .ndim - return Dimention
- .shape - return tuple of number of element in given array and Dimention 
- slicing.
- .reshape - you can make changes in array in Dimentions (any one argument is -1 which set it by system)
-  iteration - by using loop accessing elements of array
- .concatenate((array1,array2))
- .array_split
- .where
- .sort
- .operation

In [14]:
import numpy as np 
a = np.array(2)
print("Dimention is : ",a.ndim,"D")
print("A : ",a)
print(a.shape)

Dimention is :  0 D
A :  2
()


In [15]:
import numpy as np 
a = np.array([10,20,30,40])
print("Dimention is : ",a.ndim,"D")
print("A : ",a)
print(a.shape)

Dimention is :  1 D
A :  [10 20 30 40]
(4,)


In [16]:
import numpy as np 
a = np.array([10,20,30,40])
print("Dimention is : ",a.ndim,"D")
print("A : ",a)
print(a.shape)

Dimention is :  1 D
A :  [10 20 30 40]
(4,)


In [17]:
import numpy as np 
a = np.array([[10,20,30],[40,50,60]])
print("Dimention is : ",a.ndim,"D")
print("A : ",a)
print(a.shape)

Dimention is :  2 D
A :  [[10 20 30]
 [40 50 60]]
(2, 3)


In [21]:
import numpy as np 
a = np.array([[[10,20,30,40],[50,60,70,80]],[[100,200,300,400],[500,600,700,800]]])
print("Dimention is : ",a.ndim,"D")
print("A : ",a)
print(a.shape)

Dimention is :  3 D
A :  [[[ 10  20  30  40]
  [ 50  60  70  80]]

 [[100 200 300 400]
  [500 600 700 800]]]
(2, 2, 4)


In [23]:
import numpy as np 
a = np.array([[[[1,2,3]]]])
print("Dimention is : ",a.ndim,"D")
print("A : ",a)
print(a.shape)

Dimention is :  4 D
A :  [[[[1 2 3]]]]
(1, 1, 1, 3)


In [25]:
import numpy as np 
a = np.array([[1,2,3,4,],[5,6,7,8]])
print(a[:,1:4])

[[2 3 4]
 [6 7 8]]


In [28]:
import numpy as np 
a = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[51,52,53,54,55],[61,62,63,64,65],[71,72,73,74,75]]])
print(a.shape)
print(a[:,1:,2:])


(2, 3, 5)
[[[ 8  9 10]
  [13 14 15]]

 [[63 64 65]
  [73 74 75]]]


In [30]:
import numpy as np 
a = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[51,52,53,54,55],[61,62,63,64,65],[71,72,73,74,75]]])
print(a.shape)
print(a[1:,:,1:3])


(2, 3, 5)
[[[52 53]
  [62 63]
  [72 73]]]


In [34]:
import numpy as np 
a = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[51,52,53,54,55],[61,62,63,64,65],[71,72,73,74,75]]])
print(a[:,::2,1::2])

[[[ 2  4]
  [12 14]]

 [[52 54]
  [72 74]]]


In [38]:
import numpy as np 
a = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[51,52,53,54,55],[61,62,63,64,65],[71,72,73,74,75]]])
print(a[:,0,1])

[ 2 52]


In [46]:
import numpy as np 
a = np.array((1,2,3,4,5,6))
print(a)
a = a.reshape(1,3,2,-1)
print(a)

[1 2 3 4 5 6]
[[[[1]
   [2]]

  [[3]
   [4]]

  [[5]
   [6]]]]


In [49]:
import numpy as np 
a = np.array(range(1,51)).reshape(2,5,5)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [53]:
import numpy as np 
a = np.array([[1,2],[3,4],[5,6]])
a = a.reshape(-1)
print(a)

[1 2 3 4 5 6]


In [62]:
import numpy as np
a = np.array(range(1,19)).reshape(2,3,3)
print(a)
s = 0
for i in a[:,:,1].reshape(-1):
    s += i
print(s)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
57


In [64]:
# 1D
import numpy as np
a1 = np.array([1,2,3,4])
a2 = np.array([4,5,6,7])
print(a1.shape)
n = np.concatenate((a1,a2))
print(n)
print(n.shape)

(4,)
[1 2 3 4 4 5 6 7]
(8,)


In [73]:
# 2D
import numpy as np
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[10,11],[13,14],[15,16]])
print(a1.shape)
print(a2.shape)
n = np.concatenate((a1,a2),axis=1)
print(n)
print(n.shape)

(3, 3)
(3, 2)
[[ 1  2  3 10 11]
 [ 4  5  6 13 14]
 [ 7  8  9 15 16]]
(3, 5)


In [6]:
# 3D
import numpy as np
a1 = np.array(range(1,13)).reshape(2,3,-1)
print(a1.shape)
a2 = np.array(range(21,33)).reshape(2,3,-1)
print(a2.shape)
n = np.concatenate((a1,a2),axis=2)
print(n.shape)

(2, 3, 2)
(2, 3, 2)
(2, 3, 4)


In [5]:
import numpy as np
a1 = np.array(range(1,25)).reshape(3,2,4)
print(a1)
for i in a1:
    for j in i:
        if(j[3]==12):
            print(j[3])
            break

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
12


In [17]:
import numpy as np
a1 = np.array(range(1,25)).reshape(3,2,4)
a2 = np.array(range(51,75)).reshape(3,2,4)
print(a1.shape)
print(a2.shape)
n = np.concatenate((a1,a2),axis=2)
print(n.shape)
print(n)

(3, 2, 4)
(3, 2, 4)
(3, 2, 8)
[[[ 1  2  3  4 51 52 53 54]
  [ 5  6  7  8 55 56 57 58]]

 [[ 9 10 11 12 59 60 61 62]
  [13 14 15 16 63 64 65 66]]

 [[17 18 19 20 67 68 69 70]
  [21 22 23 24 71 72 73 74]]]


In [27]:
# array_split for 1D
import numpy as np 
a = np.array([1,2,3,4,5,6])
x = np.array_split(a,2)
print(x)
print("--------------------")
for i in x:
    print(i)
print("--------------------")
print(x[1])

[array([1, 2, 3]), array([4, 5, 6])]
--------------------
[1 2 3]
[4 5 6]
--------------------
[4 5 6]


In [35]:
# array_split for 1D
import numpy as np 
a = np.array([1,2,3,4,5,6])
x = np.array_split(a,2)
print(x)

[array([1, 2, 3]), array([4, 5, 6])]


In [36]:
# array_split for 2D
import numpy as np 
a = np.array(range(1,13)).reshape(3,4)
print(a)
x = np.array_split(a,5,axis=1)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]]), array([], shape=(3, 0), dtype=int32)]


In [49]:
# array_split for 3D
import numpy as np 
a = np.array(range(1,25)).reshape(2,3,4)
print(a)
x = np.array_split(a,4,axis= 2)
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]]), array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]]), array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]]), array([[[ 4],
        [ 8],
        [12]],

       [[16],
        [20],
        [24]]])]


### Where : 

In [53]:
import numpy as np 
a = np.array([[1,2],[3,4],[5,6]])
x = np.where(a%2==0)
print(x)

(array([0, 1, 2], dtype=int64), array([1, 1, 1], dtype=int64))


In [59]:
import numpy as np 
a = np.array([[[2,3,9],[4,6,7]],
              [[1,3,5],[7,8,7]],
              [[16,3,4],[7,7,7]]])
x = np.where(a%2==0)
print(x)

(array([0, 0, 0, 1, 2, 2], dtype=int64), array([0, 1, 1, 1, 0, 0], dtype=int64), array([0, 0, 1, 1, 0, 2], dtype=int64))


### Sort

In [61]:
a = np.array([1,9,5,2,6])
print(np.sort(a)[::-1])

[9 6 5 2 1]


In [72]:
a1 = np.array([[9,1],
              [6,20],
              [2,5]])
a1 = np.sort(a1,axis=0) # આમા જ highest અક્સિસ default હોય છે 
print(a1)

[[ 2  1]
 [ 6  5]
 [ 9 20]]


In [82]:
import numpy as np 
a = np.array([[[2,3,9],
               [4,6,7]],
              [[1,3,5],
               [7,8,7]]])
x = np.sort(a,axis=0)
print(x)

[[[1 3 5]
  [4 6 7]]

 [[2 3 9]
  [7 8 7]]]


###  Operations : 
- it performs actual operation with every elements of arrays.