# NumPy

In [15]:
# 0D
import numpy as np
a=np.array(35)
print("Dimension: ",a.ndim)
print("shape: ",a.shape)
print(a)

Dimension:  0
()
35


In [14]:
# 1D
import numpy as np
a=np.array([1,2,3,4])
print("Dimension: ",a.ndim)
print("shape: ",a.shape)
print(a)

Dimension:  1
(4,)
[1 2 3 4]


In [13]:
# 2D
import numpy as np
a=np.array([[1,2,3],[5,6,7]])
print("Dimension: ",a.ndim)
print("shape: ",a.shape)
print(a)

Dimension:  2
(2, 3)
[[1 2 3]
 [5 6 7]]


In [19]:
# 3D
import numpy as np
a=np.array([[[1,2,3],[5,6,7]],[[3,2,1],[6,5,4]],[[3,2,1],[6,5,4]]])
print("Dimension: ",a.ndim)
print("shape: ",a.shape)
print(a)

Dimension:  3
shape:  (3, 2, 3)
[[[1 2 3]
  [5 6 7]]

 [[3 2 1]
  [6 5 4]]

 [[3 2 1]
  [6 5 4]]]


In [20]:
# 4D
import numpy as np
a=np.array([[[[1,2,3],[5,6,7]],[[3,2,1],[6,5,4]],[[3,2,1],[6,5,4]]],[[[1,2,3],[5,6,7]],[[3,2,1],[6,5,4]],[[3,2,1],[6,5,4]]]])
print("Dimension: ",a.ndim)
print("shape: ",a.shape)
print(a)

Dimension:  4
shape:  (2, 3, 2, 3)
[[[[1 2 3]
   [5 6 7]]

  [[3 2 1]
   [6 5 4]]

  [[3 2 1]
   [6 5 4]]]


 [[[1 2 3]
   [5 6 7]]

  [[3 2 1]
   [6 5 4]]

  [[3 2 1]
   [6 5 4]]]]


In [21]:
# 4D
import numpy as np
a=np.array([[[[1,2,3]]]])
print("Dimension: ",a.ndim)
print("shape: ",a.shape)
print(a)

Dimension:  4
shape:  (1, 1, 1, 3)
[[[[1 2 3]]]]


In [24]:
# slicing
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[:,1:4])

[[2 3 4]
 [7 8 9]]


In [35]:
import numpy as np
a=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[51,52,53,54,55],[61,62,63,64,65],[71,72,73,74,75]]])
print(a[:,1:,2:])
print("===============")
print(a[1:,:,1:3])
print("===============")
print(a[:,::2,1::2])
print("===============")
print(a[:,:1,1:2])

[[[ 8  9 10]
  [13 14 15]]

 [[63 64 65]
  [73 74 75]]]
[[[52 53]
  [62 63]
  [72 73]]]
[[[ 2  4]
  [12 14]]

 [[52 54]
  [72 74]]]
[[[ 2]]

 [[52]]]


In [46]:
#reshape
import numpy as np
a=np.array((1,2,3,4,5,6))
a=a.reshape(3,2)
print(a)
print("===============")

a=a.reshape(2,-1)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [43]:
#reshape
import numpy as np
a=np.array(range(1,51))
print(a.reshape(2,5,5))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [49]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a.reshape(-1))

[1 2 3 4 5 6]


In [59]:
import numpy as np

a=np.array(range(1,19))
a=(a.reshape(2,3,3))
print(a)
print("===============")

print(a[:,:,1])
print("===============")

s=0
for i in a[:,:,1].reshape(-1):
    s+=i
print(s)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[ 2  5  8]
 [11 14 17]]
57


In [61]:
import numpy as np
a1=np.array((1,2,3,4))
a2=np.array((5,6,7,8))
n=np.concatenate((a1,a2))
print(n)
print(n.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [75]:
# 2D concatenate
import numpy as np
a1=np.array(range(1,10)).reshape(3,3)
a2=np.array(range(10,19)).reshape(3,3)
n=np.concatenate((a1,a2),axis=0)
print(n)
print(n.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)


In [82]:
# 3D concatenate
import numpy as np
a1=np.array(range(1,13)).reshape(2,3,2)
a2=np.array(range(21,33)).reshape(2,3,2)
n=np.concatenate((a1,a2),axis=2)
print(n)
print(n.shape)

[[[ 1  2 21 22]
  [ 3  4 23 24]
  [ 5  6 25 26]]

 [[ 7  8 27 28]
  [ 9 10 29 30]
  [11 12 31 32]]]
(2, 3, 4)
