In [26]:
# numpy: 0D, 1D, 2D, 3D, 4D, 5D
import numpy as np
l=(3,2,4)
a=np.array(range(1,25)).reshape(3,2,4)
print(a)
for i in a:
    for j in i:
        for k in j:
            if (k==12):
                print(k)
                break
for i in range(len(a)):
    for j in range((i)):
        for k in range((j)):
            if (a[i,j,k]==12):
                print(k)
                break

                
a1=np.array(range(1,25)).reshape(3,2,4)
print("===========")
print(a1)

a2=np.array(range(51,75)).reshape(3,2,4)
print("===========")
print(a2)

a3=np.concatenate((a1,a2),axis=2)
print("===========")
print(a3.shape)

print("===========")
print(a3)
print("===========")

b=np.array([1,2,3,4,5,6])
x=np.array_split(b,2)
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
12
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
[[[51 52 53 54]
  [55 56 57 58]]

 [[59 60 61 62]
  [63 64 65 66]]

 [[67 68 69 70]
  [71 72 73 74]]]
(3, 2, 8)
[[[ 1  2  3  4 51 52 53 54]
  [ 5  6  7  8 55 56 57 58]]

 [[ 9 10 11 12 59 60 61 62]
  [13 14 15 16 63 64 65 66]]

 [[17 18 19 20 67 68 69 70]
  [21 22 23 24 71 72 73 74]]]
[array([1, 2, 3]), array([4, 5, 6])]


In [32]:
a=np.array([1,2,3,4,5])
x=np.array_split(a,4)
print(x)
print("===========")
for i in x:
    print(i)
print("===========")
print(x[1])

[array([1, 2]), array([3]), array([4]), array([5])]
[1 2]
[3]
[4]
[5]
[3]


In [46]:
a=np.array(range(1,13)).reshape(3,4)
x=np.array_split(a,2,axis=1)
print(x)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [63]:
import numpy as np
a=np.array(range(1,25)).reshape(3,2,4)
print(a)
x=np.array_split(a,4,axis=2)
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
[array([[[ 1],
        [ 5]],

       [[ 9],
        [13]],

       [[17],
        [21]]]), array([[[ 2],
        [ 6]],

       [[10],
        [14]],

       [[18],
        [22]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]],

       [[19],
        [23]]]), array([[[ 4],
        [ 8]],

       [[12],
        [16]],

       [[20],
        [24]]])]


In [67]:
a=np.array([1,2,4,9,5,4,6,4])
x=np.where(a==4)
print(x)
a1=np.array(range(1,7)).reshape(3,2)
x1=np.where(a1%2==0)
print(x1)

(array([2, 5, 7], dtype=int64),)
(array([0, 1, 2], dtype=int64), array([1, 1, 1], dtype=int64))


In [70]:
a=np.array([1,9,5,2,6])
a=np.sort(a)
print(a[::-1])

[9 6 5 2 1]


In [77]:
a=np.array([[9,1],[6,20],[2,5]])
a=np.sort(a,axis=0)

print(a)

[[ 2  1]
 [ 6  5]
 [ 9 20]]


In [81]:
a=np.array([[[2,3,9],[4,6,7]],[[1,3,5],[7,8,7]]])

print(np.sort(a,axis=0))
print("===========")
print(np.sort(a,axis=1))
print("===========")
print(np.sort(a,axis=2))
print("===========")


[[[1 3 5]
  [4 6 7]]

 [[2 3 9]
  [7 8 7]]]


[[[9,2,5],[6,1,7]],
 [[3,1,4],[5,20,5]],
 [[2,10,3],[4,15,3]]]

# axis=0 sort()
[[[2,1,3],[4,1,3]],
 [[3,2,4],[5,4,5]],
 [[9,10,5],[6,20,7]]]

# axis=1 sort()
[[[6,1,5],[9,2,7]],
 [[3,1,4],[5,20,5]],
 [[2,10,3],[4,15,3]]]

# axis=2 sort()
[[[2,5,9],[1,6,7]],
 [[1,3,4],[5,5,20]],
 [[2,3,10],[3,4,15]]]